document xsuspender's autostart capability
kernc/xsuspender pull request #30
Opened 2021-12-18 20:16 UTC by tpo

... when used with desktop environments.

2021-12-18 23:32 UTC, kernc requested changes

2021-12-18 23:32 UTC, kernc commented on README.md
> +desktop's session management settings.
* You could mention this is likened to copying the file into _~/.config/autostart/_ with set `Hidden=false`.

* Please expressly mention that if the user toggles this enabled, they must be aware of and ready to face and mitigate spurious suspended app lock-ups such as in https://github.com/kernc/xsuspender/issues/11.
* Can you also please _verify_ and mention that xxuspender warnings and errors then go to _~/.xsession-errors_?

2021-12-18 23:32 UTC, kernc commented on README.md
> +For brief usage instructions, run:auto
```suggestion
For brief usage instructions, run:
```

2021-12-21 08:58 UTC, tpo commented on README.md
> +desktop's session management settings.
> Can you also please verify and mention that xxuspender warnings and errors then go to ~/.xsession-errors?

I see that xsuspender is running (started by xfce4-session), however I can't see any entries of xsuspender in `~/.xsession-errors`. Should there be any? Is there a way to manually trigger xsuspender to produce some output?

Also I see that the following paragraph about debugging is mentioning that xsuspender will log to `~/.xession-errors`. I can split that phrase off into its own little subchapter so that I don't have to repeat it in the autostart paragraph?

2021-12-21 11:52 UTC, kernc commented on README.md
> +desktop's session management settings.
Ah, ok, I see that's already mentioned. :sweat_smile: I think it works when `G_MESSAGES_DEBUG` is set (I hope I didn't make this up), so it must be the case with any calls to [`g_warning`](https://github.com/kernc/xsuspender/search?q=g_warning) and [`g_error`](https://github.com/kernc/xsuspender/search?q=g_critical) also. You can raise those e.g. by an invalid config file.

Then I'd just move the whole section _under_ `#### Configuration debugging` section.

2021-12-21 11:53 UTC, kernc commented on README.md
> +#### automatically starting xsuspender
Prefer: _Auto-start with desktop session_. Title-case first word for sure.

2021-12-21 11:54 UTC, kernc commented on README.md
> +suspended app lock-ups such as in #11 and be ready to mitigate them.
Need hyperlink to issue: https://github.com/kernc/xsuspender/issues/11

2021-12-21 18:11 UTC, tpo commented on README.md
> +desktop's session management settings.
I'm confirming that indeed errors appear in ~/.xession-errors when xsuspender is autostarted.

I've split the mention of the log off into it's own subchapter so it stands out and is immediately visible from both the "debugging" and the "autostart" chapters.

Commited in https://github.com/tpo/xsuspender/commit/1e49cf7612b312817a576fa8c3508e98f1621097

That should address the final one of the points you brought up. Wanna pull?

2021-12-21 18:12 UTC, tpo commented on README.md
> +suspended app lock-ups such as in #11 and be ready to mitigate them.
Yeah, I thought writing hastag 11 would create the link. Will fix it.

2021-12-21 18:19 UTC, tpo commented on README.md
> +#### automatically starting xsuspender
Title is upcased. However "Auto-start with desktop session" is too much jargon for me. I think "automatically starting xsuspender" is clearer as in simpler to understand: the reader doesn't have parse what a "desktop session" is. Also this is the first time I see the word "auto-start".

I'll certainly change the title if you insist however I think it's less well readable.

2021-12-21 23:46 UTC, kernc commented on README.md
> +suspended app lock-ups such as in https://github.com/kernc/xsuspender/issues/11
```suggestion
suspended app lock-ups such as in [GH-11](https://github.com/kernc/xsuspender/issues/11)
```

2021-12-21 23:51 UTC, kernc commented
Lgtm, thanks!

2021-12-21 23:52 UTC, merged

2021-12-22 06:55 UTC, tpo commented
> Lgtm, thanks!

Thanks @kernc !